# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'imagepicker2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for imagepicker2

  # required by RN
  pod 'React', :path => '../node_modules/react-native', subspecs: ['Core', 'RCTImage', "CxxBridge"]
   # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

   # Third party deps podspec link - required by RN
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  # image picker pod
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'


end






